### ISSUE TITLE
How to define CommonStates in DataTemplate?

### ISSUE THREAD

**Issue by HppZ** [futurice/windows-app-development-best-practices#30]
just like Normal, PointerOver, Pressed states. Do they work? if not, why?

**Comment by jarnmo** [comment]
You should just be able to do it like the first example in here: https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.VisualStateManager (just replace ControlTemplate with DataTemplate). 

However, it seems that if you want to use adaptive triggers in your states, you have to wrap things into a UserControl as described here: https://github.com/futurice/windows-app-development-best-practices#visualstates-with-adaptivetriggers-in-a-datatemplate-have-to-be-wrapped-into-a-usercontrol
